CREATE TABLE IF NOT EXISTS PRODUCTS(
PRODUCT_ID TEXT PRIMARY KEY,
PRODUCT_NAME TEXT,
UNIT TEXT,
PRICE REAL
);
INSERT INTO PRODUCTS(PRODUCT_ID,PRODUCT_NAME,UNIT,PRICE)VALUES
('1','Sajid Facewash','200 ML*2 BOX',450),
('2','Sajid Lotion','450 ML*5 BOX',650),
('3','Safwan Sunscreen','400 ML*1 BOX',700),
('4','Afnan Baby Oil','1200 ML*60 BOX',1400),
('5','Afnan Serum','8 ML*10 BOX',800);

SELECT COUNT(PRODUCT_ID) AS Product_ID FROM PRODUCTS;
SELECT AVG(PRICE) AS Average_Price FROM PRODUCTS;
SELECT SUM(PRICE) AS Total_Price FROM PRODUCTS;